dependencies:
  - name: helm-toolkit
    repository: https://opendev.org/openstack/openstack-helm-infra.git
  - name: mysql
    repository: https://github.com/helm/charts.git
  - name: telegraf
    repository: https://github.com/helm/charts.git
