dependencies:
  - name: mysql
    from:
      name: mysql
      repo: https://github.com/rbalagopalakrishna/nested/tree/master/nested-helm/nested/charts/mysql
  - name: telegraf
    from:
      name: telegraf
      repo: https://github.com/rbalagopalakrishna/nested/tree/master/nested-helm/nested/charts/telegraf
